Feature/create pair generator service
GFLCourses5/worker pull request #113
Opened 2023-10-04 12:14 UTC by dead1nsideq

Added defaultProxy logic to DefaultPairGeneratorService

2023-10-04 12:14 UTC, OlexTul approved these changes

2023-10-04 13:13 UTC, Sokol3783 requested changes

2023-10-04 13:13 UTC, Sokol3783 commented on src/main/java/executor/service/service/parallelflowexecutor/impls/subscribers/DefaultPairGeneratorService.java
> +            scenarios = scenarioQueue.getAllScenario();
Why do you declare variable in one place and initialize in another?

2023-10-04 13:13 UTC, Sokol3783 commented on src/main/java/executor/service/service/parallelflowexecutor/impls/subscribers/DefaultPairGeneratorService.java
> +                pairs = createMixPairs(proxies, scenarios);
it's better create separate method, it's going be more clear and efficient

2023-10-04 13:13 UTC, Sokol3783 commented on src/main/java/executor/service/service/parallelflowexecutor/impls/subscribers/DefaultPairGeneratorService.java
> +                }
better to hide this if/else in one function with common signature, and like this (but try to find out better name) :
return combineProxiesAndScenarios(proxies, scenario);

2023-10-04 13:13 UTC, Sokol3783 commented on src/main/java/executor/service/service/parallelflowexecutor/impls/subscribers/DefaultPairGeneratorService.java
> +            }
There are four main cases:
1. scenarios and proxy has the same size
2. scenarios and proxy has different size, and both of them more than zero
3. there are no proxy
4. there are no scenarios

you describe three cases, but what will happen with proxy if there no scenarios?

2023-10-04 14:37 UTC, IfLunatic approved these changes

2023-10-04 16:43 UTC, Mercurialf approved these changes

2023-10-06 09:24 UTC, Sokol3783 approved these changes

2023-10-06 09:24 UTC, merged