Create Test ProxyNetworkConfig
GFLCourses5/worker pull request #12
Opened 2023-08-02 10:31 UTC by Mercurialf

2023-08-02 11:35 UTC, jurok3x requested changes

2023-08-02 11:35 UTC, jurok3x commented on src/test/java/executor/service/model/ProxyNetworkConfigTest.java
> +        Integer port = 8080;
extract constants

2023-08-02 11:35 UTC, jurok3x commented on src/test/java/executor/service/model/ProxyNetworkConfigTest.java
> +    public void testEqualsAndHashCode() {
separate this test

2023-08-02 11:35 UTC, jurok3x commented on src/test/java/executor/service/model/ProxyNetworkConfigTest.java
> +        assertEquals(port, config.getPort());
no need to test separate fields when object equal() doing it all.
see lecture video.

2023-08-02 14:20 UTC, dead1nsideq commented on src/test/java/executor/service/model/ProxyNetworkConfigTest.java
> +    }
Better do beforeEach method

2023-08-02 15:08 UTC, OlexTul commented
package executor.service.model;

import org.junit.Test;

import static org.junit.Assert.*;

public class ProxyNetworkConfigTest {

    @Test
    public void testEqualsAndHashCode() {
        ProxyNetworkConfig config1 = new ProxyNetworkConfig("example.com", 8080);
        ProxyNetworkConfig config2 = new ProxyNetworkConfig("example.com", 8080);
        ProxyNetworkConfig config3 = new ProxyNetworkConfig("different.com", 8080);

        // Test equals method
        assertEquals(config1, config2);
        assertNotEquals(config1, config3);

        // Test hashCode method
        assertEquals(config1.hashCode(), config2.hashCode());
        assertNotEquals(config1.hashCode(), config3.hashCode());
    }

    @Test
    public void testGettersAndSetters() {
        ProxyNetworkConfig config = new ProxyNetworkConfig();

        config.setHostname("example.com");
        config.setPort(8080);

        assertEquals("example.com", config.getHostname());
        assertEquals(Long.valueOf(8080L), Long.valueOf(config.getPort()));
    }
}

2023-08-03 05:53 UTC, OlexTul commented
I would do like as :
package executor.service.model;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.*;
import static org.junit.Assert.assertEquals;

public class ProxyNetworkConfigTest {
    private static final String HOSTNAME = "example.com";
    private static final String HOSTNAME_ANOTHER = "example.org";
    private static final Integer PORT = 8080;
    private static final Integer PORT_ANOTHER = 8081;
    private ProxyNetworkConfig config1;
    private ProxyNetworkConfig config2;
    private ProxyNetworkConfig config3;

    @Before
    public void setUp() {
        config1 = new ProxyNetworkConfig(HOSTNAME, PORT);
        config2 = new ProxyNetworkConfig(HOSTNAME, PORT);
        config3 = new ProxyNetworkConfig(HOSTNAME_ANOTHER, PORT_ANOTHER);
    }

    @After
    public void tearDown() {
        config1 = null;
        config2 = null;
        config3 = null;
    }

    @Test
    public void testEmptyConstructor() {
        ProxyNetworkConfig config = new ProxyNetworkConfig();
        assertNull(config.getHostname());
        assertNull(config.getPort());
    }

    @Test
    public void testParameterizedConstructorAndSetters() {
        ProxyNetworkConfig config = new ProxyNetworkConfig();
        config.setHostname(HOSTNAME);
        config.setPort(PORT);

        assertEquals(config, config1);
    }

    @Test
    public void testEquals() {
        assertEquals(config1, config2);
        assertNotEquals(config1, config3);
    }

    @Test
    public void testHashCode() {
        assertEquals(config1.hashCode(), config2.hashCode());
        assertNotEquals(config1.hashCode(), config3.hashCode());
    }
}

2023-08-03 07:31 UTC, merged