Spring security test
GFLCourses5/worker pull request #123
Opened 2023-10-17 19:51 UTC by Sokol3783

Simple test for web-chain

2023-10-21 07:32 UTC, OlexTul requested changes

2023-10-21 07:32 UTC, OlexTul commented on src/test/java/executor/service/security/SecurityTest.java
> +package executor.service.security;
I recommend placing this class in **package executor.service.config;**

2023-10-22 15:43 UTC, OlexTul approved these changes

2023-10-25 16:19 UTC, git-alexbondarenko approved these changes

2023-10-25 16:53 UTC, merged