ParallelFlowExecutor service by Yurii Kotsiuba
GFLCourses5/worker pull request #69
Opened 2023-09-14 14:50 UTC by jurok3x

My implementation of ParallelFlowExecutor.

2023-09-14 15:24 UTC, OlexTul requested changes

2023-09-14 15:24 UTC, OlexTul commented on src/main/java/executor/service/service/ParallelFlowExecutorService.java
> +    void run();
Why did you change the name of the method, this contradicts the contract.

2023-09-14 15:24 UTC, OlexTul commented on src/main/java/executor/service/service/impl/ParallelFlowExecutorServiceImpl.java
> +
In my opinion, here, we should still stick to the Java documentation and implement the **shutdown()** method as a good practice.

2023-09-14 15:24 UTC, OlexTul commented on src/main/java/executor/service/service/impl/ParallelFlowExecutorServiceImpl.java
> +            while (true) {
Here you should provide a correct exit from the loop **while{}**.

2023-09-14 15:24 UTC, OlexTul commented on src/main/java/executor/service/service/impl/ParallelFlowExecutorServiceImpl.java
> +            System.err.printf("Error while running Thread: %s", e.getMessage());
It would be better to use logging here.

2023-09-14 19:04 UTC, dead1nsideq approved these changes

2023-09-14 19:05 UTC, Sokol3783 approved these changes

2023-09-14 19:05 UTC, Sokol3783 commented on src/main/java/executor/service/service/impl/ParallelFlowExecutorServiceImpl.java
> +            System.err.printf("Error while running Thread: %s", e.getMessage());
I'm agree

2023-09-16 14:01 UTC, Mercurialf approved these changes

2023-09-30 08:59 UTC, closed without merging