-refactor WebDriverInitializerImpl;
GFLCourses5/worker pull request #82
Opened 2023-09-22 13:31 UTC by git-alexbondarenko

-move extension creation logic to ChromeProxyPlugin; 
-add browser version and chrome path properties

2023-09-22 16:47 UTC, OlexTul approved these changes

2023-09-22 17:41 UTC, IfLunatic approved these changes

2023-09-23 14:40 UTC, Mercurialf approved these changes

2023-09-23 20:06 UTC, jurok3x requested changes

2023-09-23 20:06 UTC, jurok3x commented on src/main/resources/web-driver.properties
> +chrome-executable=/opt/google/chrome/chrome
please use env variables

2023-09-30 12:53 UTC, merged